# Generated by Django 6.0.6 on 2026-06-26 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_fix_soft_delete_unique_constraint'),
        ('employees', '0002_alter_department_head'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('req_id', models.CharField(editable=False, help_text='Auto-generated HRID (e.g., REQ7K3M9)', max_length=20, null=True, unique=True)),
                ('reason', models.TextField(help_text="Employee's justification for needing this asset")),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Request priority', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', help_text='Current request status', max_length=20)),
                ('review_notes', models.TextField(blank=True, default='', help_text='Notes from the reviewing admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to='categories.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_requests', to='employees.employee')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset request',
                'verbose_name_plural': 'asset requests',
                'db_table': 'asset_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='asset_reque_organiz_b9ae5d_idx'), models.Index(fields=['requested_by'], name='asset_reque_request_99ef84_idx')],
            },
        ),
    ]
