# Generated by Django 6.0.6 on 2026-06-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_id',
            field=models.CharField(editable=False, help_text='Auto-generated HRID (e.g., NOT7K3M9)', max_length=20, null=True, unique=True),
        ),
    ]
