# Generated by Django 6.0.6 on 2026-06-29 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0002_notification_notif_id'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('object_id', models.PositiveIntegerField(help_text='ID of the expiring object')),
                ('notification_type', models.CharField(choices=[('asset_allocated', 'Asset Allocated'), ('request_approved', 'Request Approved'), ('request_rejected', 'Request Rejected'), ('incident_update', 'Incident Update'), ('incident_assigned', 'Incident Assigned'), ('license_expiry', 'License Expiry'), ('warranty_expiry', 'Warranty Expiry'), ('approval_needed', 'Approval Needed')], help_text='What kind of notification was sent', max_length=30)),
                ('threshold_days', models.PositiveIntegerField(help_text='Days before expiry (30, 14, 7, 1, 0)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, help_text='When this notification was sent')),
                ('content_type', models.ForeignKey(help_text='Type of the expiring object (license, asset, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_audits', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification audit',
                'verbose_name_plural': 'notification audits',
                'db_table': 'notification_audits',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'threshold_days'], name='notificatio_content_12e574_idx'), models.Index(fields=['organization', 'notification_type'], name='notificatio_organiz_e676bb_idx')],
                'unique_together': {('content_type', 'object_id', 'threshold_days', 'sent_at')},
            },
        ),
    ]
