# Generated by Django 6.0.6 on 2026-06-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationaudit',
            name='object_id',
            field=models.CharField(help_text='ID of the expiring object (UUID)', max_length=36),
        ),
    ]
