# Generated by Django 6.0.6 on 2026-06-29 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0004_alter_notificationaudit_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='related_content_type',
            field=models.ForeignKey(blank=True, help_text='Type of the related object (license, request, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, help_text='HRID of the related object (e.g., LIC7K3M9, REQ9M3K1)', max_length=20, null=True),
        ),
    ]
