# Generated by Django 6.0.6 on 2026-06-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0005_alter_notification_related_content_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationaudit',
            unique_together={('content_type', 'object_id', 'threshold_days', 'notification_type')},
        ),
    ]
