# Generated by Django 6.0.6 on 2026-06-25 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_fix_soft_delete_unique_constraint'),
        ('employees', '0002_alter_department_head'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('asset_code', models.CharField(editable=False, help_text='Auto-generated sequential asset code (e.g., AST-2026-00001)', max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('serial_number', models.CharField(blank=True, default='', help_text='Manufacturer serial / VIN number', max_length=255)),
                ('brand', models.CharField(blank=True, default='', help_text='Brand / manufacturer name', max_length=255)),
                ('model_name', models.CharField(blank=True, default='', help_text='Model name or number', max_length=255)),
                ('purchase_date', models.DateField(blank=True, help_text='Date the asset was purchased', null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text="Purchase price in organization's base currency", max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiration date', null=True)),
                ('status', models.CharField(choices=[('procured', 'Procured'), ('available', 'Available'), ('allocated', 'Allocated'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='available', help_text='Current lifecycle status of the asset', max_length=20)),
                ('location', models.CharField(blank=True, default='', help_text='Physical location or storage location of the asset', max_length=255)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee this asset is currently allocated to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='employees.employee')),
                ('category', models.ForeignKey(blank=True, help_text='Asset category this asset belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='categories.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset',
                'verbose_name_plural': 'assets',
                'db_table': 'assets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='assets_organiz_6b50f0_idx'), models.Index(fields=['organization', 'is_active'], name='assets_organiz_12ffd1_idx'), models.Index(fields=['category'], name='assets_categor_840335_idx'), models.Index(fields=['assigned_to'], name='assets_assigne_36a4dc_idx'), models.Index(fields=['status', 'is_active'], name='assets_status_51f646_idx')],
            },
        ),
    ]
