# Generated by Django 6.0.6 on 2026-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_code',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(editable=False, help_text='Auto-generated sequential asset ID (e.g., AST-2026-00001)', max_length=20, null=True, unique=True),
        ),
    ]
