# Generated by Django 6.0.6 on 2026-06-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_asset_asset_code_asset_asset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(editable=False, help_text='Auto-generated HRID (e.g., AST7K3M9)', max_length=20, null=True, unique=True),
        ),
    ]
