# Generated by Django 6.0.6 on 2026-06-26 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocations', '0001_initial'),
        ('employees', '0002_alter_department_head'),
        ('inventory', '0003_alter_asset_asset_id'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('asset',), name='unique_active_allocation'),
        ),
    ]
