# Generated by Django 6.0.6 on 2026-06-30 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('allocate', 'Allocate'), ('approve', 'Approve'), ('reject', 'Reject')], help_text='Type of action performed.', max_length=20)),
                ('model_name', models.CharField(help_text='Model class name (e.g. Asset, Incident).', max_length=100)),
                ('object_id', models.UUIDField(help_text='UUID primary key of the affected object.')),
                ('old_data', models.JSONField(blank=True, help_text='Serialized state before the change.', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='Serialized state after the change.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the action.', null=True)),
                ('request_id', models.UUIDField(blank=True, help_text='Correlation ID (X-Request-ID) for request tracing.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (from request context).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_org_created_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_model_object_idx'), models.Index(fields=['action'], name='audit_action_idx')],
            },
        ),
    ]
