# Generated by Django 6.0.6 on 2026-06-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='audit_id',
            field=models.CharField(editable=False, help_text='Human-readable ID (e.g. AUD7K3M9).', max_length=20, null=True, unique=True),
        ),
    ]
