# Generated by Django 6.0.6 on 2026-06-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_audit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='new_data',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='old_data',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text="Change snapshot: {'old': {...}, 'new': {...}}.", null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, help_text='URL path of the request (e.g., /api/v1/assets/AST7K3M9/).', max_length=255, null=True),
        ),
    ]
