# Generated by Django 6.0.6 on 2026-06-29 04:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_department_head'),
        ('inventory', '0003_alter_asset_asset_id'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('inc_id', models.CharField(editable=False, help_text='Auto-generated HRID (e.g., INC7K3M9)', max_length=20, null=True, unique=True)),
                ('title', models.CharField(help_text='Brief title for the incident', max_length=300)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('category', models.CharField(choices=[('hardware', 'Hardware'), ('software', 'Software'), ('physical_damage', 'Physical Damage'), ('performance', 'Performance'), ('other', 'Other')], help_text='Incident category', max_length=50)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', help_text='Current incident status', max_length=20)),
                ('resolution_notes', models.TextField(blank=True, default='', help_text='Notes on how the incident was resolved')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file URLs')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the incident was marked resolved', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Timestamp when the incident was closed', null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='inventory.asset')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Employee assigned to handle this incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to='employees.employee')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='organizations.organization')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to='employees.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'db_table': 'incidents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='incidents_organiz_866fc8_idx'), models.Index(fields=['asset'], name='incidents_asset_i_2db974_idx'), models.Index(fields=['reported_by'], name='incidents_reporte_8c329b_idx')],
            },
        ),
    ]
