# Generated by Django 6.0.6 on 2026-06-25 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cat_id', models.CharField(editable=False, help_text='Human-readable unique ID (auto-generated)', max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_categories', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category. Leave blank to create a top-level category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='categories.assetcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asset category',
                'verbose_name_plural': 'asset categories',
                'db_table': 'asset_categories',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='asset_categ_organiz_030449_idx'), models.Index(fields=['organization', 'is_active'], name='asset_categ_organiz_66bd3f_idx'), models.Index(fields=['parent'], name='asset_categ_parent__bff2f2_idx')],
                'unique_together': {('organization', 'name')},
            },
        ),
    ]
