# Generated by Django 6.0.6 on 2026-06-25 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assetcategory',
            name='asset_categ_organiz_030449_idx',
        ),
        migrations.AlterUniqueTogether(
            name='assetcategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assetcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'name'), name='unique_active_category_name_per_org'),
        ),
    ]
