# Generated by Django 6.0.6 on 2026-06-25 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Employee who heads this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='employees.employee'),
        ),
    ]
