# Generated by Django 6.0.6 on 2026-06-29 06:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_alter_department_head'),
        ('inventory', '0003_alter_asset_asset_id'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lic_id', models.CharField(editable=False, help_text='Auto-generated HRID (e.g., LIC7K3M9)', max_length=20, null=True, unique=True)),
                ('software_name', models.CharField(help_text='Name of the software', max_length=255)),
                ('license_key', models.CharField(blank=True, default='', help_text='License key or activation code', max_length=500)),
                ('license_type', models.CharField(choices=[('per_user', 'Per User'), ('per_device', 'Per Device'), ('site', 'Site')], help_text='License type (per_user, per_device, site)', max_length=20)),
                ('total_seats', models.PositiveIntegerField(help_text='Total number of available seats')),
                ('expiry_date', models.DateField(blank=True, help_text='License expiry date', null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Purchase cost', max_digits=12, null=True)),
                ('vendor', models.CharField(blank=True, default='', help_text='Software vendor', max_length=255)),
                ('document', models.FileField(blank=True, help_text='License document or receipt', null=True, upload_to='licenses/docs/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='software_licenses', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'software license',
                'verbose_name_plural': 'software licenses',
                'db_table': 'software_licenses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LicenseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When this assignment was revoked', null=True)),
                ('asset', models.ForeignKey(blank=True, help_text='Asset assigned this license', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='inventory.asset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Employee assigned this license', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_assignments', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='licenses.softwarelicense')),
            ],
            options={
                'verbose_name': 'license assignment',
                'verbose_name_plural': 'license assignments',
                'db_table': 'license_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='softwarelicense',
            index=models.Index(fields=['organization', 'license_type'], name='software_li_organiz_a2ea64_idx'),
        ),
        migrations.AddIndex(
            model_name='softwarelicense',
            index=models.Index(fields=['expiry_date'], name='software_li_expiry__fbd745_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['license', 'revoked_at'], name='license_ass_license_46dfaa_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['employee'], name='license_ass_employe_89813c_idx'),
        ),
        migrations.AddIndex(
            model_name='licenseassignment',
            index=models.Index(fields=['asset'], name='license_ass_asset_i_6bfe9b_idx'),
        ),
    ]
