# Generated by Django 6.0.6 on 2026-06-29 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_department_head'),
        ('inventory', '0003_alter_asset_asset_id'),
        ('licenses', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='licenseassignment',
            constraint=models.CheckConstraint(condition=models.Q(('employee__isnull', False), ('asset__isnull', False), _connector='OR'), name='employee_or_asset_required'),
        ),
    ]
