# Generated by Django 6.0.6 on 2026-07-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_licenseassignment_employee_or_asset_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
