# Generated by Django 6.0.6 on 2026-06-24 11:42

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('org_id', models.CharField(editable=False, help_text='Human-readable unique ID (auto-generated)', max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-safe identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.TextField(blank=True, default='')),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Organization logo image', null=True, upload_to='org_logos/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'db_table': 'organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('default_timezone', models.CharField(default='UTC', help_text='IANA timezone string (e.g., Asia/Kolkata)', max_length=63)),
                ('working_hours_start', models.TimeField(default=datetime.time(9, 0, tzinfo=datetime.timezone.utc), help_text='Start of working day (HH:MM)')),
                ('working_hours_end', models.TimeField(default=datetime.time(18, 0, tzinfo=datetime.timezone.utc), help_text='End of working day (HH:MM)')),
                ('working_days', models.JSONField(blank=True, default=list, help_text='List of weekdays as integers 0–6 (0=Monday). E.g., [0,1,2,3,4] for Mon–Fri.')),
                ('asset_code_prefix', models.CharField(blank=True, default='', help_text='Prefix for auto-generated asset codes', max_length=20)),
                ('request_approval_required', models.BooleanField(default=True, help_text='Whether asset requests need org admin approval')),
                ('auto_approve_requests', models.BooleanField(default=False, help_text='Auto-approve requests up to this count per employee per month')),
                ('max_requests_per_month', models.PositiveIntegerField(default=0, help_text='Max requests per employee per month (0 = unlimited, only if auto_approve is on)')),
                ('notify_on_asset_allocated', models.BooleanField(default=True)),
                ('notify_on_asset_returned', models.BooleanField(default=True)),
                ('notify_on_request_submitted', models.BooleanField(default=True)),
                ('notify_on_request_approved', models.BooleanField(default=True)),
                ('notify_on_request_rejected', models.BooleanField(default=True)),
                ('notify_on_incident_reported', models.BooleanField(default=True)),
                ('notify_on_incident_resolved', models.BooleanField(default=True)),
                ('admin_user', models.ForeignKey(blank=True, help_text='Primary admin user for this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_organizations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization config',
                'verbose_name_plural': 'organization configs',
                'db_table': 'organization_configs',
            },
        ),
    ]
